version: '3.5'
services:
  nbadb:
    build: ./DatabaseServerContainer
    network_mode: "host"
    volumes:
      - ./DatabaseServerContainer:/DatabaseServerContainer

  dashboard:
    build: ./ClientServerContainer
    depends_on:
      - nbadb
    network_mode: "host"
    volumes:
      - ./ClientServerContainer:/ClientServerContainer